# SwiftLint configuration following Google Swift Style Guide

disabled_rules:
  - todo
  - orphaned_doc_comment
  - unused_capture_list
  - trailing_whitespace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

included:
  - RuckMap
  - RuckMapTests

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage
  - .swiftpm
  - "**/.build"

line_length:
  warning: 100
  error: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - w
    - h
    - i
    - j
    - k
    - n
    - m
    - q
    - r
    - t
    - G
    - L
    - V
    - W
    - MR

vertical_whitespace:
  max_empty_lines: 1

trailing_whitespace:
  ignores_empty_lines: true

indentation_width:
  indentation_width: 4

custom_rules:
  array_constructor:
    name: "Array Constructor"
    regex: 'Array<(.+)>'
    capture_group: 1
    message: "Use array shorthand syntax instead"
    severity: warning

  double_space:
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning

  print_usage:
    name: "Print Usage"
    regex: '(^|\s)print\('
    message: "Use proper logging instead of print statements"
    severity: warning

  ns_number_usage:
    name: "NSNumber Usage"
    regex: 'NSNumber'
    message: "Use Swift native numeric types instead of NSNumber"
    severity: warning