disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
excluded:
  - Carthage
  - Pods
  - .build
line_length:
  warning: 120
  error: 150