name: RuckMap
options:
  bundleIdPrefix: com.ruckmap
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  DEVELOPMENT_TEAM: ""
  SWIFT_VERSION: "6.0"
  SWIFT_STRICT_CONCURRENCY: complete
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  IPHONEOS_DEPLOYMENT_TARGET: 18.0
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
targets:
  RuckMap:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - RuckMap
    settings:
      INFOPLIST_FILE: RuckMap/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.ruckmap.RuckMap
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
    capabilities:
      com.apple.BackgroundModes:
        enabled: true
        modes:
          - location
          - processing
      com.apple.HealthKit:
        enabled: true
      com.apple.developer.associated-domains:
        enabled: false
    scheme:
      testTargets:
        - RuckMapTests
      gatherCoverageData: true
  RuckMapTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - RuckMapTests
    dependencies:
      - target: RuckMap
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/RuckMap.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/RuckMap
      GENERATE_INFOPLIST_FILE: YES