name: RuckMap
options:
  bundleIdPrefix: com.ruckmap
  developmentTeam: ""
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "6.0"
    ENABLE_STRICT_OBJC_MSGSEND: "YES"
    ENABLE_TESTABILITY: "YES"
    GCC_NO_COMMON_BLOCKS: "YES"
    CLANG_ENABLE_MODULES: "YES"
    CLANG_ENABLE_OBJC_ARC: "YES"
    CLANG_ENABLE_OBJC_WEAK: "YES"
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
    CLANG_WARN_BOOL_CONVERSION: "YES"
    CLANG_WARN_COMMA: "YES"
    CLANG_WARN_CONSTANT_CONVERSION: "YES"
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
    CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
    CLANG_WARN_EMPTY_BODY: "YES"
    CLANG_WARN_ENUM_CONVERSION: "YES"
    CLANG_WARN_INFINITE_RECURSION: "YES"
    CLANG_WARN_INT_CONVERSION: "YES"
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
    CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
    CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: "YES"
    CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
    CLANG_WARN_STRICT_PROTOTYPES: "YES"
    CLANG_WARN_SUSPICIOUS_MOVE: "YES"
    CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
    CLANG_WARN_UNREACHABLE_CODE: "YES"
    CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
    COPY_PHASE_STRIP: "NO"
    DEBUG_INFORMATION_FORMAT: "dwarf"
    ENABLE_NS_ASSERTIONS: "NO"
    ENABLE_STRICT_OBJC_MSGSEND: "YES"
    GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
    GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
    GCC_WARN_UNDECLARED_SELECTOR: "YES"
    GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
    GCC_WARN_UNUSED_FUNCTION: "YES"
    GCC_WARN_UNUSED_VARIABLE: "YES"
    MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
    MTL_FAST_MATH: "YES"
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
packages:
  TelemetryDeck:
    url: https://github.com/TelemetryDeck/SwiftSDK
    from: "2.0.0"
  WishKit:
    url: https://github.com/wishkit/wishkit-ios
    from: "4.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm
    from: "5.0.0"
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
targets:
  RuckMap:
    type: application
    platform: iOS
    sources:
      - RuckMap
    resources:
      - RuckMap/Assets.xcassets
      - RuckMap/Preview Content
    dependencies:
      - package: TelemetryDeck
        product: TelemetryDeck
      - package: WishKit
        product: WishKit
      - package: RevenueCat
        products:
          - RevenueCat
          - RevenueCatUI
      - package: Firebase
        products:
          - FirebaseCrashlytics
          - FirebaseAnalytics
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ruckmap.RuckMap
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "RuckMap needs your location to track your rucking routes and calculate accurate distance and elevation data."
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "RuckMap needs your location to track your rucking routes even when the app is in the background."
        INFOPLIST_KEY_NSHealthShareUsageDescription: "RuckMap reads your health data to provide personalized fitness insights and track your progress."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "RuckMap saves your rucking workouts to Apple Health to keep all your fitness data in one place."
        INFOPLIST_KEY_NSMotionUsageDescription: "RuckMap uses motion data to improve the accuracy of your rucking metrics and detect when you're moving."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
        DEVELOPMENT_ASSET_PATHS: "\"RuckMap/Preview Content\""
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
  RuckMapTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - RuckMapTests
    dependencies:
      - target: RuckMap
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/RuckMap.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/RuckMap"
        GENERATE_INFOPLIST_FILE: "YES"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
  RuckMapUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - RuckMapUITests
    dependencies:
      - target: RuckMap
    settings:
      base:
        TEST_TARGET_NAME: RuckMap
        GENERATE_INFOPLIST_FILE: "YES"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
schemes:
  RuckMap:
    build:
      targets:
        RuckMap: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - RuckMapTests
        - RuckMapUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release